"""create school and student tables

Revision ID: f0b05ebdb0fb
Revises: 
Create Date: 2026-06-12 12:20:24.769790

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f0b05ebdb0fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
